[project]
name = "waha"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.14.3",
    "alembic>=1.19.2",
    "asyncpg>=0.31.0",
    "google-api-python-client>=2.200.0",
    "google-auth>=2.57.1",
    "google-genai>=2.22.0",
    "logging>=0.4.9.6",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "sqlalchemy>=2.0.52",
]
